### ISSUE TITLE
implement `std::borrow::Borrow<str>` and `std::convert::AsRef<str>` for `Owned` and `Borrowed`

### ISSUE THREAD

**Issue by Emilgardis** [neoeinstein/aliri_braid#5]
Would it be possible to implement `std::borrow::Borrow<str>` and `std::convert::AsRef<str>` for `Owned` and `Borrowed`?

This would be very useful, and I don't see any reason to not have this.

**Comment by neoeinstein** [comment]
I think so. In an earlier iteration, I had implemented `AsRef<str>` but pulled it because I wasn't as happy about the ambiguity between `AsRef` implementations. Now that I've added `as_str()`, I think that I can add an inherent method that provides access to the borrowed version. That should allow for this request and the associated boost in ergonomics with stringly-typed interfaces while still favoring the use of the borrowed form.

I'll see if I can throw this together this week.

**Comment by neoeinstein** [comment]
I will be able to implement `AsRef<str>` for all types, but I can only implement `Borrow<str>` for braids that are not normalized. If the type is normalized, then strings that might otherwise be normalized to be equal would not be able to be directly compared with a string equality. That breaks the implicit contract for `Borrow<T>`. I've added a comment about this restriction in the documentation. For someone that _really_ wants this anyway, they can go ahead and implement `Borrow<str>` for their braid outside of the macro.

**Comment by neoeinstein** [comment]
Now released as 0.1.7.
